# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './extractdatawidget.ui'
#
# Created: Tue Jun 21 13:26:36 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ExtractDataWidget(object):
    def setupUi(self, ExtractDataWidget):
        ExtractDataWidget.setObjectName("ExtractDataWidget")
        ExtractDataWidget.setEnabled(True)
        ExtractDataWidget.resize(1258, 678)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ExtractDataWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupFolder = QtGui.QGroupBox(ExtractDataWidget)
        self.groupFolder.setObjectName("groupFolder")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupFolder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.groupFolder)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlLabel = QtGui.QLabel(self.groupFolder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlLabel.sizePolicy().hasHeightForWidth())
        self.urlLabel.setSizePolicy(sizePolicy)
        self.urlLabel.setObjectName("urlLabel")
        self.horizontalLayout.addWidget(self.urlLabel)
        self.openFolderButton = QtGui.QPushButton(self.groupFolder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFolderButton.sizePolicy().hasHeightForWidth())
        self.openFolderButton.setSizePolicy(sizePolicy)
        self.openFolderButton.setObjectName("openFolderButton")
        self.horizontalLayout.addWidget(self.openFolderButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.folderStatusLabel = QtGui.QLabel(self.groupFolder)
        self.folderStatusLabel.setText("")
        self.folderStatusLabel.setObjectName("folderStatusLabel")
        self.verticalLayout.addWidget(self.folderStatusLabel)
        self.verticalLayout_5.addWidget(self.groupFolder)
        self.groupConf = QtGui.QGroupBox(ExtractDataWidget)
        self.groupConf.setObjectName("groupConf")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupConf)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtGui.QFrame(self.groupConf)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.minLabel_2 = QtGui.QLabel(self.frame_2)
        self.minLabel_2.setObjectName("minLabel_2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.minLabel_2)
        self.salMinValue = QtGui.QSpinBox(self.frame_2)
        self.salMinValue.setMaximum(999999999)
        self.salMinValue.setObjectName("salMinValue")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.salMinValue)
        self.maxLabel_2 = QtGui.QLabel(self.frame_2)
        self.maxLabel_2.setObjectName("maxLabel_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.maxLabel_2)
        self.salMaxValue = QtGui.QSpinBox(self.frame_2)
        self.salMaxValue.setMaximum(999999999)
        self.salMaxValue.setObjectName("salMaxValue")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.salMaxValue)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 1, 2, 1)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.groupConf)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.minLabel = QtGui.QLabel(self.frame)
        self.minLabel.setObjectName("minLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.minLabel)
        self.cytMinValue = QtGui.QSpinBox(self.frame)
        self.cytMinValue.setMaximum(999999999)
        self.cytMinValue.setObjectName("cytMinValue")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cytMinValue)
        self.maxLabel = QtGui.QLabel(self.frame)
        self.maxLabel.setObjectName("maxLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.maxLabel)
        self.cytMaxValue = QtGui.QSpinBox(self.frame)
        self.cytMaxValue.setMaximum(999999999)
        self.cytMaxValue.setObjectName("cytMaxValue")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cytMaxValue)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 2, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.extractionStatusLabel_2 = QtGui.QLabel(self.groupConf)
        self.extractionStatusLabel_2.setText("")
        self.extractionStatusLabel_2.setObjectName("extractionStatusLabel_2")
        self.horizontalLayout_4.addWidget(self.extractionStatusLabel_2)
        spacerItem1 = QtGui.QSpacerItem(344, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.groupConf)
        self.groupBox_2 = QtGui.QGroupBox(ExtractDataWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.extractButton = QtGui.QPushButton(self.groupBox_2)
        self.extractButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractButton.sizePolicy().hasHeightForWidth())
        self.extractButton.setSizePolicy(sizePolicy)
        self.extractButton.setObjectName("extractButton")
        self.horizontalLayout_2.addWidget(self.extractButton)
        self.progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.status = QtGui.QLabel(self.groupBox_2)
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.extractionStatusLabel = QtGui.QLabel(self.groupBox_2)
        self.extractionStatusLabel.setText("")
        self.extractionStatusLabel.setObjectName("extractionStatusLabel")
        self.verticalLayout_2.addWidget(self.extractionStatusLabel)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(ExtractDataWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.profileButton = QtGui.QPushButton(self.groupBox_3)
        self.profileButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileButton.sizePolicy().hasHeightForWidth())
        self.profileButton.setSizePolicy(sizePolicy)
        self.profileButton.setObjectName("profileButton")
        self.horizontalLayout_6.addWidget(self.profileButton)
        self.correlateButton = QtGui.QPushButton(self.groupBox_3)
        self.correlateButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlateButton.sizePolicy().hasHeightForWidth())
        self.correlateButton.setSizePolicy(sizePolicy)
        self.correlateButton.setObjectName("correlateButton")
        self.horizontalLayout_6.addWidget(self.correlateButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.resetButton = QtGui.QPushButton(ExtractDataWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)

        self.retranslateUi(ExtractDataWidget)
        QtCore.QMetaObject.connectSlotsByName(ExtractDataWidget)

    def retranslateUi(self, ExtractDataWidget):
        ExtractDataWidget.setWindowTitle(QtGui.QApplication.translate("ExtractDataWidget", "Extract data from CellProfiler", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFolder.setTitle(QtGui.QApplication.translate("ExtractDataWidget", "1. Select folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExtractDataWidget", "Select the folder where are CellProfiler raw data (.csv files):", None, QtGui.QApplication.UnicodeUTF8))
        self.urlLabel.setText(QtGui.QApplication.translate("ExtractDataWidget", "No folder yet !", None, QtGui.QApplication.UnicodeUTF8))
        self.openFolderButton.setText(QtGui.QApplication.translate("ExtractDataWidget", "Open folder", None, QtGui.QApplication.UnicodeUTF8))
        self.groupConf.setTitle(QtGui.QApplication.translate("ExtractDataWidget", "2. Configure the extraction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ExtractDataWidget", "Salmonella diameter :", None, QtGui.QApplication.UnicodeUTF8))
        self.minLabel_2.setText(QtGui.QApplication.translate("ExtractDataWidget", "Min :", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLabel_2.setText(QtGui.QApplication.translate("ExtractDataWidget", "Max :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ExtractDataWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">Here you can exclude salmonella according their diameters.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExtractDataWidget", "Cytoplasm diameter :", None, QtGui.QApplication.UnicodeUTF8))
        self.minLabel.setText(QtGui.QApplication.translate("ExtractDataWidget", "Min :", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLabel.setText(QtGui.QApplication.translate("ExtractDataWidget", "Max :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExtractDataWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic;\">Here you can exclude cytoplasms according their diameters.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ExtractDataWidget", "3. Make the extraction", None, QtGui.QApplication.UnicodeUTF8))
        self.extractButton.setText(QtGui.QApplication.translate("ExtractDataWidget", "Extract data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ExtractDataWidget", "4. Build profile", None, QtGui.QApplication.UnicodeUTF8))
        self.profileButton.setText(QtGui.QApplication.translate("ExtractDataWidget", "Build profiles with \"Profile Visualizer\" ", None, QtGui.QApplication.UnicodeUTF8))
        self.correlateButton.setText(QtGui.QApplication.translate("ExtractDataWidget", "Correlate parameters with \"Correlation Analizer\" ", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("ExtractDataWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))

