# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './correlate/correlationwidget.ui'
#
# Created: Tue Jun 21 13:26:35 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CorrelationWidget(object):
    def setupUi(self, CorrelationWidget):
        CorrelationWidget.setObjectName("CorrelationWidget")
        CorrelationWidget.resize(1116, 658)
        self.verticalLayout = QtGui.QVBoxLayout(CorrelationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(CorrelationWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.splitter)
        self.scrollArea_2 = QtGui.QScrollArea(CorrelationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1368, 60))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.status = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setFrameShape(QtGui.QFrame.NoFrame)
        self.status.setText("")
        self.status.setScaledContents(True)
        self.status.setWordWrap(True)
        self.status.setObjectName("status")
        self.horizontalLayout.addWidget(self.status)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loadButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.drawButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.drawButton.setObjectName("drawButton")
        self.horizontalLayout.addWidget(self.drawButton)
        self.importWellsButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.importWellsButton.setObjectName("importWellsButton")
        self.horizontalLayout.addWidget(self.importWellsButton)
        self.switchModeButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.switchModeButton.setObjectName("switchModeButton")
        self.horizontalLayout.addWidget(self.switchModeButton)
        self.tightButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.tightButton.setObjectName("tightButton")
        self.horizontalLayout.addWidget(self.tightButton)
        self.toggleSelectedButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.toggleSelectedButton.setObjectName("toggleSelectedButton")
        self.horizontalLayout.addWidget(self.toggleSelectedButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)

        self.retranslateUi(CorrelationWidget)
        QtCore.QMetaObject.connectSlotsByName(CorrelationWidget)

    def retranslateUi(self, CorrelationWidget):
        CorrelationWidget.setWindowTitle(QtGui.QApplication.translate("CorrelationWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Load .csv", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Save current table as .csv", None, QtGui.QApplication.UnicodeUTF8))
        self.drawButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Draw the correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.importWellsButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Highlight control wells", None, QtGui.QApplication.UnicodeUTF8))
        self.switchModeButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Toggle correlation / distance mode", None, QtGui.QApplication.UnicodeUTF8))
        self.tightButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Toggle loose / tight mode", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleSelectedButton.setText(QtGui.QApplication.translate("CorrelationWidget", "Select / Unselect all", None, QtGui.QApplication.UnicodeUTF8))

